local mod = get_mod("VoiceOnDemand")

if mod._icons_module then return mod._icons_module end

local PATHS = {
  "content/ui/materials/icons/abilities/combat/default",
  "content/ui/materials/icons/abilities/default",
  "content/ui/materials/icons/abilities/throwables/default",
  "content/ui/materials/icons/character_creator/accomplishment",
  "content/ui/materials/icons/character_creator/appearence",
  "content/ui/materials/icons/character_creator/appearence_cryptic",
  "content/ui/materials/icons/character_creator/appearence_ogryn",
  "content/ui/materials/icons/character_creator/childhood",
  "content/ui/materials/icons/character_creator/companion_appearence",
  "content/ui/materials/icons/character_creator/growth",
  "content/ui/materials/icons/character_creator/home_planet",
  "content/ui/materials/icons/character_creator/home_planet_broker",
  "content/ui/materials/icons/character_creator/personality",
  "content/ui/materials/icons/character_creator/sentence",
  "content/ui/materials/icons/circumstances/assault_01",
  "content/ui/materials/icons/circumstances/darkness_01",
  "content/ui/materials/icons/circumstances/darkness_02",
  "content/ui/materials/icons/circumstances/darkness_03",
  "content/ui/materials/icons/circumstances/darkness_04",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_ember",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_encroaching_garden",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_fading_light_1",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_fading_light_2",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_final_toll",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_heinous_rituals",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_moebian21st",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_nurgle",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_parasite",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_rampaging_enemies",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_rotten_armor",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_skin",
  "content/ui/materials/icons/circumstances/havoc/havoc_mutator_stimmed_minions",
  "content/ui/materials/icons/circumstances/havoc_pj/havoc_mutator_rotten_armor",
  "content/ui/materials/icons/circumstances/hunting_grounds_01",
  "content/ui/materials/icons/circumstances/hunting_grounds_02",
  "content/ui/materials/icons/circumstances/hunting_grounds_03",
  "content/ui/materials/icons/circumstances/less_resistance_01",
  "content/ui/materials/icons/circumstances/live_event_01",
  "content/ui/materials/icons/circumstances/maelstrom_01",
  "content/ui/materials/icons/circumstances/maelstrom_02",
  "content/ui/materials/icons/circumstances/more_resistance_01",
  "content/ui/materials/icons/circumstances/nurgle_manifestation_01",
  "content/ui/materials/icons/circumstances/six_one_01",
  "content/ui/materials/icons/circumstances/special_waves_01",
  "content/ui/materials/icons/circumstances/special_waves_02",
  "content/ui/materials/icons/circumstances/special_waves_03",
  "content/ui/materials/icons/circumstances/ventilation_purge_01",
  "content/ui/materials/icons/circumstances/ventilation_purge_02",
  "content/ui/materials/icons/circumstances/ventilation_purge_03",
  "content/ui/materials/icons/circumstances/ventilation_purge_04",
  "content/ui/materials/icons/classes/adamant",
  "content/ui/materials/icons/classes/adamant_terminal",
  "content/ui/materials/icons/classes/broker",
  "content/ui/materials/icons/classes/broker_terminal",
  "content/ui/materials/icons/classes/cryptic",
  "content/ui/materials/icons/classes/cryptic_terminal",
  "content/ui/materials/icons/classes/ogryn",
  "content/ui/materials/icons/classes/ogryn_terminal",
  "content/ui/materials/icons/classes/psyker",
  "content/ui/materials/icons/classes/psyker_terminal",
  "content/ui/materials/icons/classes/veteran",
  "content/ui/materials/icons/classes/veteran_terminal",
  "content/ui/materials/icons/classes/zealot",
  "content/ui/materials/icons/classes/zealot_terminal",
  "content/ui/materials/icons/contracts/complexity_easy",
  "content/ui/materials/icons/contracts/complexity_hard",
  "content/ui/materials/icons/contracts/complexity_medium",
  "content/ui/materials/icons/contracts/complexity_tutorial",
  "content/ui/materials/icons/contracts/contracts_store/unknown_melee_weapon",
  "content/ui/materials/icons/contracts/contracts_store/unknown_ranged_weapon",
  "content/ui/materials/icons/contracts/contract_task",
  "content/ui/materials/icons/cosmetics/categories/headgear",
  "content/ui/materials/icons/cosmetics/categories/lower_body",
  "content/ui/materials/icons/cosmetics/categories/upper_body",
  "content/ui/materials/icons/crafting/enhance_item",
  "content/ui/materials/icons/crafting/extract_trait",
  "content/ui/materials/icons/crafting/replace_trait",
  "content/ui/materials/icons/crafting/reroll_perk",
  "content/ui/materials/icons/crafting/upgrade_item",
  "content/ui/materials/icons/currencies/credits_big",
  "content/ui/materials/icons/currencies/diamantine_big",
  "content/ui/materials/icons/currencies/experience_big",
  "content/ui/materials/icons/currencies/live_events/leftover_live_event_large",
  "content/ui/materials/icons/currencies/live_events/leftover_live_event_medium",
  "content/ui/materials/icons/currencies/live_events/leftover_live_event_small",
  "content/ui/materials/icons/currencies/live_events/saints_live_event_large",
  "content/ui/materials/icons/currencies/live_events/saints_live_event_medium",
  "content/ui/materials/icons/currencies/live_events/saints_live_event_small",
  "content/ui/materials/icons/currencies/live_events/skulls_live_event_small",
  "content/ui/materials/icons/currencies/marks_big",
  "content/ui/materials/icons/currencies/plasteel_big",
  "content/ui/materials/icons/currencies/premium_big",
  "content/ui/materials/icons/currencies/salvage_big",
  "content/ui/materials/icons/currencies/stolen_rations/rations_live_event_medium",
  "content/ui/materials/icons/currencies/tech_remnant_big",
  "content/ui/materials/icons/difficulty/difficulty_indicator_empty",
  "content/ui/materials/icons/difficulty/difficulty_indicator_full",
  "content/ui/materials/icons/difficulty/difficulty_skull_auric",
  "content/ui/materials/icons/difficulty/difficulty_skull_damnation",
  "content/ui/materials/icons/difficulty/difficulty_skull_heresy",
  "content/ui/materials/icons/difficulty/difficulty_skull_malice",
  "content/ui/materials/icons/difficulty/difficulty_skull_uprising",
  "content/ui/materials/icons/difficulty/flat/difficulty_skull_auric",
  "content/ui/materials/icons/difficulty/flat/difficulty_skull_damnation",
  "content/ui/materials/icons/difficulty/flat/difficulty_skull_heresy",
  "content/ui/materials/icons/difficulty/flat/difficulty_skull_malice",
  "content/ui/materials/icons/difficulty/flat/difficulty_skull_uprising",
  "content/ui/materials/icons/difficulty/selection_frame_dimond_small",
  "content/ui/materials/icons/engrams/engram_rarity_04",
  "content/ui/materials/icons/generic/animated/arrows_right",
  "content/ui/materials/icons/generic/bookmark",
  "content/ui/materials/icons/generic/danger",
  "content/ui/materials/icons/generic/havoc",
  "content/ui/materials/icons/generic/hourglass",
  "content/ui/materials/icons/generic/loot",
  "content/ui/materials/icons/generic/selected_item",
  "content/ui/materials/icons/generic/voice",
  "content/ui/materials/icons/items/attachments/defensive/empty",
  "content/ui/materials/icons/items/attachments/tactical/empty",
  "content/ui/materials/icons/items/attachments/utility/empty",
  "content/ui/materials/icons/items/default",
  "content/ui/materials/icons/items/emotes/emote_wheel_icon",
  "content/ui/materials/icons/items/equipped_label",
  "content/ui/materials/icons/items/gears/arms/empty",
  "content/ui/materials/icons/items/gears/head/empty",
  "content/ui/materials/icons/items/gears/legs/empty",
  "content/ui/materials/icons/items/salvage_circle",
  "content/ui/materials/icons/items/salvage_middle",
  "content/ui/materials/icons/items/weapons/melee/empty",
  "content/ui/materials/icons/items/weapons/ranged/empty",
  "content/ui/materials/icons/item_types/accessories",
  "content/ui/materials/icons/item_types/body_tattoos",
  "content/ui/materials/icons/item_types/body_types",
  "content/ui/materials/icons/item_types/boons",
  "content/ui/materials/icons/item_types/cryptic_arms",
  "content/ui/materials/icons/item_types/cryptic_height",
  "content/ui/materials/icons/item_types/cryptic_legs",
  "content/ui/materials/icons/item_types/cryptic_lens_color",
  "content/ui/materials/icons/item_types/cryptic_torso",
  "content/ui/materials/icons/item_types/devices",
  "content/ui/materials/icons/item_types/emotes",
  "content/ui/materials/icons/item_types/eye_color",
  "content/ui/materials/icons/item_types/face_tattoos",
  "content/ui/materials/icons/item_types/face_types",
  "content/ui/materials/icons/item_types/facial_hair_styles",
  "content/ui/materials/icons/item_types/facial_makeup",
  "content/ui/materials/icons/item_types/full_body_tattoos",
  "content/ui/materials/icons/item_types/fur_color",
  "content/ui/materials/icons/item_types/fur_pattern",
  "content/ui/materials/icons/item_types/hair_styles",
  "content/ui/materials/icons/item_types/headgears",
  "content/ui/materials/icons/item_types/lower_bodies",
  "content/ui/materials/icons/item_types/melee_weapons",
  "content/ui/materials/icons/item_types/nameplates",
  "content/ui/materials/icons/item_types/outfits",
  "content/ui/materials/icons/item_types/poses",
  "content/ui/materials/icons/item_types/ranged_weapons",
  "content/ui/materials/icons/item_types/scars",
  "content/ui/materials/icons/item_types/upper_bodies",
  "content/ui/materials/icons/item_types/weapons",
  "content/ui/materials/icons/item_types/weapon_skins",
  "content/ui/materials/icons/item_types/weapon_trinkets",
  "content/ui/materials/icons/list_buttons/block",
  "content/ui/materials/icons/list_buttons/box",
  "content/ui/materials/icons/list_buttons/check",
  "content/ui/materials/icons/list_buttons/cross",
  "content/ui/materials/icons/mission_difficulty_complete/difficulty_completed_1",
  "content/ui/materials/icons/mission_difficulty_complete/difficulty_completed_2",
  "content/ui/materials/icons/mission_difficulty_complete/difficulty_completed_3",
  "content/ui/materials/icons/mission_difficulty_complete/difficulty_completed_4",
  "content/ui/materials/icons/mission_difficulty_complete/difficulty_completed_5",
  "content/ui/materials/icons/mission_type/default",
  "content/ui/materials/icons/mission_types/expedition_node_symbol",
  "content/ui/materials/icons/mission_types/mission_type_01",
  "content/ui/materials/icons/mission_types/mission_type_02",
  "content/ui/materials/icons/mission_types/mission_type_03",
  "content/ui/materials/icons/mission_types/mission_type_04",
  "content/ui/materials/icons/mission_types/mission_type_05",
  "content/ui/materials/icons/mission_types/mission_type_06",
  "content/ui/materials/icons/mission_types/mission_type_07",
  "content/ui/materials/icons/mission_types/mission_type_event",
  "content/ui/materials/icons/mission_types/mission_type_expeditions",
  "content/ui/materials/icons/mission_types/mission_type_horde",
  "content/ui/materials/icons/mission_types/mission_type_operations",
  "content/ui/materials/icons/mission_types/mission_type_quick",
  "content/ui/materials/icons/mission_types/mission_type_side",
  "content/ui/materials/icons/mission_types_pj/mission_type_01",
  "content/ui/materials/icons/mission_types_pj/mission_type_02",
  "content/ui/materials/icons/mission_types_pj/mission_type_03",
  "content/ui/materials/icons/mission_types_pj/mission_type_04",
  "content/ui/materials/icons/mission_types_pj/mission_type_05",
  "content/ui/materials/icons/mission_types_pj/mission_type_06",
  "content/ui/materials/icons/mission_types_pj/mission_type_07",
  "content/ui/materials/icons/mission_types_pj/mission_type_deadside_locked",
  "content/ui/materials/icons/mission_types_pj/mission_type_event",
  "content/ui/materials/icons/mission_types_pj/mission_type_expeditions",
  "content/ui/materials/icons/mission_types_pj/mission_type_horde",
  "content/ui/materials/icons/mission_types_pj/mission_type_maelstrom_01",
  "content/ui/materials/icons/mission_types_pj/mission_type_operations",
  "content/ui/materials/icons/mission_types_pj/mission_type_quick",
  "content/ui/materials/icons/mission_types_pj/mission_type_side",
  "content/ui/materials/icons/mission_types_pj/mission_type_story",
  "content/ui/materials/icons/notifications/tech_dropped",
  "content/ui/materials/icons/npc_portraits/mission_givers/alice_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/brahms_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/darinda_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/enginseer_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/explicator_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/hestia_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/melk_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/pilot_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/procter_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/rannick_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/sefoni_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/sergeant_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/swagger_a_small",
  "content/ui/materials/icons/npc_portraits/mission_givers/tech_priest_a_small",
  "content/ui/materials/icons/objectives/bonus",
  "content/ui/materials/icons/objectives/main",
  "content/ui/materials/icons/objectives/secondary",
  "content/ui/materials/icons/perks/perk_level_01",
  "content/ui/materials/icons/perks/perk_level_02",
  "content/ui/materials/icons/perks/perk_level_03",
  "content/ui/materials/icons/perks/perk_level_04",
  "content/ui/materials/icons/perks/perk_level_05",
  "content/ui/materials/icons/pickups/default",
  "content/ui/materials/icons/player_states/dead",
  "content/ui/materials/icons/player_states/incapacitated",
  "content/ui/materials/icons/player_states/lugged",
  "content/ui/materials/icons/portraits/minion_portraits/beast_of_nurgle_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/bomber_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/chaos_hound_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/chaos_ogryn_houndmaster_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/chaos_spawn_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/mutant_portrait",
  "content/ui/materials/icons/portraits/minion_portraits/scab_trapper_portrait",
  "content/ui/materials/icons/portraits/status_blocked",
  "content/ui/materials/icons/portraits/status_party",
  "content/ui/materials/icons/portraits/status_party_invite",
  "content/ui/materials/icons/presets/preset_01",
  "content/ui/materials/icons/presets/preset_02",
  "content/ui/materials/icons/presets/preset_03",
  "content/ui/materials/icons/presets/preset_04",
  "content/ui/materials/icons/presets/preset_05",
  "content/ui/materials/icons/presets/preset_06",
  "content/ui/materials/icons/presets/preset_07",
  "content/ui/materials/icons/presets/preset_08",
  "content/ui/materials/icons/presets/preset_09",
  "content/ui/materials/icons/presets/preset_10",
  "content/ui/materials/icons/presets/preset_11",
  "content/ui/materials/icons/presets/preset_12",
  "content/ui/materials/icons/presets/preset_13",
  "content/ui/materials/icons/presets/preset_14",
  "content/ui/materials/icons/presets/preset_15",
  "content/ui/materials/icons/presets/preset_16",
  "content/ui/materials/icons/presets/preset_17",
  "content/ui/materials/icons/presets/preset_18",
  "content/ui/materials/icons/presets/preset_19",
  "content/ui/materials/icons/presets/preset_20",
  "content/ui/materials/icons/presets/preset_21",
  "content/ui/materials/icons/presets/preset_22",
  "content/ui/materials/icons/presets/preset_23",
  "content/ui/materials/icons/presets/preset_24",
  "content/ui/materials/icons/presets/preset_25",
  "content/ui/materials/icons/presets/preset_new",
  "content/ui/materials/icons/system/escape/achievements",
  "content/ui/materials/icons/system/escape/change_character",
  "content/ui/materials/icons/system/escape/credits",
  "content/ui/materials/icons/system/escape/inventory",
  "content/ui/materials/icons/system/escape/leave_mission",
  "content/ui/materials/icons/system/escape/leave_party",
  "content/ui/materials/icons/system/escape/leave_training",
  "content/ui/materials/icons/system/escape/news",
  "content/ui/materials/icons/system/escape/party_finder",
  "content/ui/materials/icons/system/escape/premium_store",
  "content/ui/materials/icons/system/escape/quit",
  "content/ui/materials/icons/system/escape/settings",
  "content/ui/materials/icons/system/escape/social",
  "content/ui/materials/icons/system/escape/social_empty",
  "content/ui/materials/icons/system/page_arrow",
  "content/ui/materials/icons/system/page_indicator_02_active",
  "content/ui/materials/icons/system/page_indicator_02_idle",
  "content/ui/materials/icons/system/page_indicator_active",
  "content/ui/materials/icons/system/return",
  "content/ui/materials/icons/system/settings/category_audio",
  "content/ui/materials/icons/system/settings/category_controls",
  "content/ui/materials/icons/system/settings/category_gameplay",
  "content/ui/materials/icons/system/settings/category_interface",
  "content/ui/materials/icons/system/settings/category_keybindings",
  "content/ui/materials/icons/system/settings/category_video",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_assault",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_bfg",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_dot",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_killshot",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_shotgun",
  "content/ui/materials/icons/system/settings/dropdown/icon_crosshair_spray_n_pray",
  "content/ui/materials/icons/system/settings/dropdown/icon_response_curve_dynamic",
  "content/ui/materials/icons/system/settings/dropdown/icon_response_curve_exponential",
  "content/ui/materials/icons/system/settings/dropdown/icon_response_curve_linear",
  "content/ui/materials/icons/traits/empty",
  "content/ui/materials/icons/weapons/actions/activate",
  "content/ui/materials/icons/weapons/actions/ads",
  "content/ui/materials/icons/weapons/actions/brace",
  "content/ui/materials/icons/weapons/actions/charge",
  "content/ui/materials/icons/weapons/actions/defence",
  "content/ui/materials/icons/weapons/actions/flashlight",
  "content/ui/materials/icons/weapons/actions/hipfire",
  "content/ui/materials/icons/weapons/actions/linesman",
  "content/ui/materials/icons/weapons/actions/melee",
  "content/ui/materials/icons/weapons/actions/melee_hand",
  "content/ui/materials/icons/weapons/actions/ninjafencer",
  "content/ui/materials/icons/weapons/actions/quick_grenade",
  "content/ui/materials/icons/weapons/actions/smiter",
  "content/ui/materials/icons/weapons/actions/special_attack",
  "content/ui/materials/icons/weapons/actions/special_bullet",
  "content/ui/materials/icons/weapons/actions/tank",
  "content/ui/materials/icons/weapons/actions/vent",
  "content/ui/materials/icons/weapons/flat/grenade",
  "content/ui/materials/icons/weapons/flat/knife",
  "content/ui/materials/icons/weapons/flat/rifle",
  "content/ui/materials/icons/abilities/frames/background_progress",
  "content/ui/materials/icons/abilities/frames/inner_line_thick_progress",
  "content/ui/materials/icons/abilities/frames/inner_line_thin",
  "content/ui/materials/icons/abilities/frames/outer_line_progress",
  "content/ui/materials/icons/achievements/achievement_icon_container",
  "content/ui/materials/icons/achievements/achievement_icon_container_v2",
  "content/ui/materials/icons/buffs/hud/buff_container_with_background",
  "content/ui/materials/icons/circumstances/placeholder",
  "content/ui/materials/icons/classes/adamant_terminal_shadow",
  "content/ui/materials/icons/classes/broker_terminal_shadow",
  "content/ui/materials/icons/classes/cryptic_terminal_shadow",
  "content/ui/materials/icons/classes/large/adamant",
  "content/ui/materials/icons/classes/large/broker",
  "content/ui/materials/icons/classes/large/cryptic",
  "content/ui/materials/icons/classes/large/ogryn",
  "content/ui/materials/icons/classes/large/psyker",
  "content/ui/materials/icons/classes/large/veteran",
  "content/ui/materials/icons/classes/large/zealot",
  "content/ui/materials/icons/classes/ogryn_terminal_shadow",
  "content/ui/materials/icons/classes/psyker_terminal_shadow",
  "content/ui/materials/icons/classes/veteran_terminal_shadow",
  "content/ui/materials/icons/classes/zealot_terminal_shadow",
  "content/ui/materials/icons/generic/animated/progression_arrows",
  "content/ui/materials/icons/generic/progression_arrows",
  "content/ui/materials/icons/hud/not_allowed",
  "content/ui/materials/icons/pocketables/hud/auspex_scanner",
  "content/ui/materials/icons/pocketables/hud/landmine_explosive",
  "content/ui/materials/icons/pocketables/hud/landmine_fire",
  "content/ui/materials/icons/pocketables/hud/landmine_shock",
  "content/ui/materials/icons/pocketables/hud/void_shield",
  "content/ui/materials/icons/talents/combat_talent_icon_container",
  "content/ui/materials/icons/talents/hud/combat_container",
  "content/ui/materials/icons/talents/hud/combat_frame_inner",
  "content/ui/materials/icons/talents/talent_icon_container",
  "content/ui/materials/icons/throwables/hud/adamant_whistle",
  "content/ui/materials/icons/throwables/hud/artillery_strike",
  "content/ui/materials/icons/throwables/hud/big_fn_grenade",
  "content/ui/materials/icons/throwables/hud/cryptic_force_field",
  "content/ui/materials/icons/throwables/hud/cryptic_servo_skull_order_shooting",
  "content/ui/materials/icons/throwables/hud/small/party_grenade",
  "content/ui/materials/icons/throwables/hud/small/party_non_grenade",
  "content/ui/materials/icons/throwables/hud/small/party_psyker",
  "content/ui/materials/icons/throwables/hud/valkyrie_hover",
  "content/ui/materials/icons/throwables/hud/valkyrie_payload",
  "content/ui/materials/icons/traits/traits_container",
  "content/ui/materials/hud/communication_wheel/icons/ammo",
  "content/ui/materials/hud/communication_wheel/icons/attention",
  "content/ui/materials/hud/communication_wheel/icons/enemy",
  "content/ui/materials/hud/communication_wheel/icons/for_the_emperor",
  "content/ui/materials/hud/communication_wheel/icons/health",
  "content/ui/materials/hud/communication_wheel/icons/location",
  "content/ui/materials/hud/communication_wheel/icons/thanks",
  "content/ui/materials/hud/icons/minion_shield_health/stamina_empty_left",
  "content/ui/materials/hud/icons/minion_shield_health/stamina_empty_right",
  "content/ui/materials/hud/icons/minion_shield_health/stamina_full",
  "content/ui/materials/hud/icons/party_ammo",
  "content/ui/materials/hud/icons/party_cohesion",
  "content/ui/materials/hud/icons/party_throwable",
  "content/ui/materials/hud/icons/player_assistance/player_assistance_frame",
  "content/ui/materials/hud/icons/player_assistance/player_assistance_glow",
  "content/ui/materials/hud/icons/speaker",
  "content/ui/materials/hud/interactions/icons/ammunition",
  "content/ui/materials/hud/interactions/icons/artillery_strike",
  "content/ui/materials/hud/interactions/icons/attention",
  "content/ui/materials/hud/interactions/icons/barber",
  "content/ui/materials/hud/interactions/icons/barrel_explosive",
  "content/ui/materials/hud/interactions/icons/big_fn_grenade",
  "content/ui/materials/hud/interactions/icons/contracts",
  "content/ui/materials/hud/interactions/icons/cosmetics_store",
  "content/ui/materials/hud/interactions/icons/credits_store",
  "content/ui/materials/hud/interactions/icons/default",
  "content/ui/materials/hud/interactions/icons/enemy",
  "content/ui/materials/hud/interactions/icons/enemy_priority",
  "content/ui/materials/hud/interactions/icons/environment_alert",
  "content/ui/materials/hud/interactions/icons/environment_generic",
  "content/ui/materials/hud/interactions/icons/expeditions",
  "content/ui/materials/hud/interactions/icons/expeditions_death",
  "content/ui/materials/hud/interactions/icons/expeditions_loot",
  "content/ui/materials/hud/interactions/icons/expeditions_salvage",
  "content/ui/materials/hud/interactions/icons/expeditions_zone",
  "content/ui/materials/hud/interactions/icons/forge",
  "content/ui/materials/hud/interactions/icons/grenade",
  "content/ui/materials/hud/interactions/icons/havoc",
  "content/ui/materials/hud/interactions/icons/help",
  "content/ui/materials/hud/interactions/icons/inbox",
  "content/ui/materials/hud/interactions/icons/landmine_explosive",
  "content/ui/materials/hud/interactions/icons/landmine_fire",
  "content/ui/materials/hud/interactions/icons/landmine_shock",
  "content/ui/materials/hud/interactions/icons/location",
  "content/ui/materials/hud/interactions/icons/mission_board",
  "content/ui/materials/hud/interactions/icons/objective_main",
  "content/ui/materials/hud/interactions/icons/objective_secondary",
  "content/ui/materials/hud/interactions/icons/objective_side",
  "content/ui/materials/hud/interactions/icons/penances",
  "content/ui/materials/hud/interactions/icons/pocketable_ammo",
  "content/ui/materials/hud/interactions/icons/pocketable_corrupted_auspex_scanner",
  "content/ui/materials/hud/interactions/icons/pocketable_default",
  "content/ui/materials/hud/interactions/icons/pocketable_medkit",
  "content/ui/materials/hud/interactions/icons/pocketable_syringe_ability",
  "content/ui/materials/hud/interactions/icons/pocketable_syringe_corruption",
  "content/ui/materials/hud/interactions/icons/pocketable_syringe_power",
  "content/ui/materials/hud/interactions/icons/pocketable_syringe_speed",
  "content/ui/materials/hud/interactions/icons/premium_store",
  "content/ui/materials/hud/interactions/icons/respawn",
  "content/ui/materials/hud/interactions/icons/resupply",
  "content/ui/materials/hud/interactions/icons/speak",
  "content/ui/materials/hud/interactions/icons/time",
  "content/ui/materials/hud/interactions/icons/time_syringe",
  "content/ui/materials/hud/interactions/icons/training_grounds",
  "content/ui/materials/hud/interactions/icons/valkyrie_hover",
  "content/ui/materials/hud/interactions/icons/valkyrie_payload",
  "content/ui/materials/hud/interactions/icons/void_shield",
  "content/ui/materials/symbols/character_level",
  "content/ui/materials/symbols/cog_big",
  "content/ui/materials/symbols/cog_small",
  "content/ui/materials/symbols/infinite",
  "content/ui/materials/symbols/logo_bishop",
  "content/ui/materials/symbols/logos/games_workshop_warhammer_logo_white",
  "content/ui/materials/symbols/warning",
}

local ICONS, _by_id, _by_legacy = {}, {}, {}

-- Re-scan PATHS for currently-loadable materials. On a fresh game boot many UI
-- material packages aren't registered yet, so can_get_resource returns false;
-- call this again later (e.g. when opening the UI) to pick them up. Mutates the
-- ICONS table in place so existing references (api.list) stay valid.
local function rebuild()
  for k in pairs(_by_id) do _by_id[k] = nil end
  for k in pairs(_by_legacy) do _by_legacy[k] = nil end
  for i = #ICONS, 1, -1 do ICONS[i] = nil end
  for _, path in ipairs(PATHS) do
    if Application.can_get_resource("material", path) then
      -- Unique id = path minus the common prefix (avoids basename collisions
      -- across roots, e.g. icons/.../attention vs hud/.../attention).
      local id = path:gsub("^content/ui/materials/", "")
      ICONS[#ICONS + 1] = { id = id, material = path }
      _by_id[id] = path
      -- Legacy alias: favourites saved before unique ids stored the basename.
      -- Use last-wins to exactly match the previous (basename) id scheme, so
      -- existing favourites keep resolving to the same icon they did before.
      local base = path:match("[^/]+$")
      _by_legacy[base] = path
    end
  end
  return #ICONS
end

rebuild()

local function material(id)
  if not id then return nil end
  return _by_id[id] or _by_legacy[id]
end

-- Lazily settle the cache. Material packages aren't loaded at game-boot
-- mod-init, so the build above is usually empty/partial. refresh() (called when
-- the UI opens) re-scans only until the count stops growing, then locks so
-- later opens are no-ops instead of re-scanning every time.
local _ready, _last_count = false, -1
local function refresh()
  if _ready then return #ICONS end
  local n = rebuild()
  if n > 0 and n == _last_count then _ready = true end
  _last_count = n
  return n
end

local api = { list = ICONS, material = material, refresh = refresh }
mod._icons_module = api
return api
